[theme]
primaryColor = "#ffffff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#111111"
textColor = "#f4f4f5"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
port = 8501
maxUploadSize = 2048
